### PR TITLE
исправления фильтра UsersFields

### PR DESCRIPTION
**Pull request by mokeev1995**
#186 

- [x] Nickname
- [x] Domain
- [x] Sex
- [x] BirthDate
- [x] City
- [x] Country
- [x] Timezone
- [x] Photo50
- [x] Photo100
- [x] Photo200Orig
- [x] Photo200
- [x] Photo400Orig
- [x] PhotoMax
- [x] PhotoMaxOrig
- [x] HasMobile
- [x] Contacts
- [x] Education
- [x] Online
- [x] OnlineMobile
- [x] FriendLists
- [x] Relation
- [x] LastSeen
- [x] Status
- [x] CanWritePrivateMessage
- [x] CanSeeAllPosts
- [x] CanPost
- [x] Universities
- [x] Connections
- [x] Site
- [x] Schools
- [x] CanSeeAudio
- [x] CommonCount 
- [x] Relatives
- [x] Counters

### CODE REVIEW

**Comment by mokeev1995** [comment]
#186

**Comment by mokeev1995** [comment]
- [x] Nickname
- [x] Domain
- [x] Sex
- [x] BirthDate
- [x] City
- [x] Country
- [x] Timezone
- [x] Photo50
- [x] Photo100
- [x] Photo200Orig
- [x] Photo200
- [x] Photo400Orig
- [x] PhotoMax
- [x] PhotoMaxOrig
- [x] HasMobile
- [x] Contacts
- [x] Education
- [x] Online
- [x] OnlineMobile
- [x] FriendLists
- [x] Relation
- [x] LastSeen
- [x] Status
- [x] CanWritePrivateMessage
- [x] CanSeeAllPosts
- [x] CanPost
- [x] Universities
- [x] Connections
- [x] Site
- [x] Schools
- [x] CanSeeAudio
- [ ] CommonCount 
- [ ] Relatives
- [ ] Counters

**Comment by mokeev1995** [comment]
Всё фиксанул

**Comment by inyutin-maxim** [comment]
@mokeev1995 Синхронизируйте изменения с нашим репозиторием и поправьте тесты которые ломают ваши изменения

**Comment by mokeev1995** [comment]
@inyutin-maxim синхронизировал, должно, думаю, все норомально работать

**Comment by inyutin-maxim** [comment]
@mokeev1995 Спасибо

**Pull request merged**
